%YAML:1.0

#common parameters
imu: 0
num_of_cam: 2  

imu_topic: ""
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
#output_path: "$ParkingRamp3D_PATH/output3D/"
#output_path: "/home/junesuk/KNU/output/"

cam0_calib: "camLeftResize.yaml"
cam1_calib: "camRightResize.yaml"
image_width: 512
image_height: 512

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

imu_T_body: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.9995250378696743, 0.029615343885863205, -0.008522328211654736, 0.04727988224914392,
          0.0075019185074052044, -0.03439736061393144, -0.9993800792498829, -0.047443232143367084,
          -0.02989013031643309, -0.998969345370175, 0.03415885127385616, -0.0681999605066297,
          0.0, 0.0, 0.0, 1.0]

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d  
   data: [0.999999445773492091, 0.000791687752816809, 0.000694034010224251, 0.101063427414194287,
         -0.000823363992157605, 0.998899461915672471, 0.046895490788700409, 0.001946204678583838,
         -0.000656143613644434, -0.046896036240589738, 0.998899560146302545, 0.001015350132563249,
         0.0, 0.0, 0.0, 0.1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 300            # max feature number in feature tracking
min_dist: 20            # min distance between two features (default: 30)
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy
stereoKernelShiftY: 21.0   # default 0.0

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# TUM VI home page cf.
acc_n: 0.0028        # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.00016         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.00086         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.000022       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
