%YAML:1.0

#common parameters
imu: 1
num_of_cam: 2  

imu_topic: "/imu/data"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"

cam0_calib: "camLeftResize.yaml"
cam1_calib: "camRightResize.yaml"
image_width: 640
image_height: 512

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

imu_T_body: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.009014590430656477, 0.0027196109606669222, -0.9999556694551971, -0.037509463164566284, 
           0.9999591913017509, -0.0005695506584758979, -0.009016171204950758, -0.05559103586041331, 
          -0.0005940458880172492, -0.9999961396566845, -0.002714365710968255, -0.038194197684952365, 
           0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0073964868943379915, 0.0015066551569644, -0.9999715105801058, -0.04008375998188167, 
          0.9999699212008093, 0.0023231567367893316, 0.007399975433979274, 0.04498968413942557, 
          0.0023342397625505506, -0.9999961664591589, -0.001489426640229337, -0.038551133916259875, 
          0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 0

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 20            # min distance between two features (default: 30)
freq: 0                 # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy
stereoKernelShiftY: 21.0

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation.
gyr_n: 0.005         # gyroscope measurement noise standard deviation
acc_w: 0.005         # accelerometer bias random work noise standard deviation.
gyr_w: 5.0e-5       # gyroscope bias random work noise standard deviation.
g_norm: 9.81007     # gravity magnitude



#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

