%YAML:1.0

# 에피폴라분해능: 0.000005296875

#common parameters
imu: 0
num_of_cam: 2  

imu_topic: ""
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
#output_path: "$ParkingRamp3D_PATH/output3D/"
#output_path: "/home/junesuk/KNU/output/"

# SIVVON data path for superPoint and superGlue
superpoint_superglue_kp_track_match_data: "/home/sivvon/Desktop/Junseok_backup_0410/knu/scanning_deep/catkin_ws_scanning_ekf_ver2/spsg_220408-electronstore-cam_imu_lidar_store1_0.05_0.5/"
vio_lidar_3d_map_path: "/home/sivvon/Desktop/Junseok_backup_0410/knu/dataset_n_output/underground_output_vio+lidar/"

cam0_calib: "camLeftResize.yaml"
cam1_calib: "camRightResize.yaml"
image_width: 640
image_height: 512

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

imu_T_body: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.009014590430656477, 0.0027196109606669222, -0.9999556694551971, -0.037509463164566284, 
           0.9999591913017509, -0.0005695506584758979, -0.009016171204950758, -0.05559103586041331, 
          -0.0005940458880172492, -0.9999961396566845, -0.002714365710968255, -0.038194197684952365,
           0.0, 0.0, 0.0, 1.0]

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d   
   data: [0.9998610507845387, 0.002903523663344857, 0.016414891848590612, 0.1006000336995435, 
         -0.0028836487118315515, 0.9999950804910845, -0.0012343272508781459, 0.000292647952264879, 
         -0.016418394993764834, 0.0011868209603409555, 0.9998645047014435, 0.001668298561366531, 
          0.0, 0.0, 0.0, 1.0]
   # data: [0.9999829392963145, -0.003891824912502756, -0.0043560090860120014, 0.09900721032586574, 
   #        0.003924115969339322, 0.9999647038476545, 0.007429156933055882, -0.0001767849035675587, 
   #        0.004326942357620715, -0.007446123671227808, 0.9999629157184333, -0.0057846960182489915, 
   #        0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 0

#feature traker paprameters
max_cnt: 400            # max feature number in feature tracking
min_dist: 10            # min distance between two features (default: 30)
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy
stereoKernelShiftY: 21.0

# SIVVON superPoint and superGlue confidence threshold
cam0_cur_keypoint_confidence_threshold: 0.1
cam0_tracking_confidence_threshold: 0.5
stereo_matching_confidence_threshold: 0.5

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.0e-4       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

